### ISSUE TITLE
各种连接错误

### ISSUE THREAD

**Issue by b1randa** [Python3WebSpider/Weixin#1]
一直报各种连接错误（基本是这三种）
(MaxRetryError("HTTPConnectionPool(host='103.218.25.193', port=8080): Max retries exceeded with url: http://weixin.sogou.com/weixin?type=2&query=gakki (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001D18D534DD8>, 'Connection to 103.218.25.193 timed out. (connect timeout=20)'))",),)

(ReadTimeoutError("HTTPConnectionPool(host='190.2.110.180', port=8080): Read timed out. (read timeout=20)",),)

(MaxRetryError("HTTPConnectionPool(host='118.25.18.67', port=80): Max retries exceeded with url: http://weixin.sogou.com/weixin?type=2&query=gakki (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))",),)

看着自己的代理池应该没什么问题.....用崔神的码也是这样的问题......请教下到底是怎么回事....

**Comment by goodbad3** [comment]
..................

**Comment by goodbad3** [comment]
有问题

**Comment by goodbad3** [comment]
Schedule http://weixin.sogou.com/weixin?query=NBA&type=2
Get Proxy 46.29.12.231:53281
(MaxRetryError("HTTPConnectionPool(host='46.29.12.231', port=53281): Max retries exceeded with url: http://weixin.sogou.com/weixin?query=NBA&type=2 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001D322CCDC18>, 'Connection to 46.29.12.231 timed out. (connect timeout=10)'))",),)
Request Failed 1 Times http://weixin.sogou.com/weixin?query=NBA&type=2
Schedule http://weixin.sogou.com/weixin?query=NBA&type=2
Get Proxy 119.28.118.116:1080
Request Failed 2 Times http://weixin.sogou.com/weixin?query=NBA&type=2
Schedule http://weixin.sogou.com/weixin?query=NBA&type=2
Get Proxy 200.229.208.154:53281
(MaxRetryError("HTTPConnectionPool(host='200.229.208.154', port=53281): Max retries exceeded with url: http://weixin.sogou.com/weixin?query=NBA&type=2 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001D322CCD080>, 'Connection to 200.229.208.154 timed out. (connect timeout=10)'))",),)
Request Failed 3 Times http://weixin.sogou.com/weixin?query=NBA&type=2
Schedule http://weixin.sogou.com/weixin?query=NBA&type=2
Get Proxy 119.27.177.169:80
Request Failed 4 Times http://weixin.sogou.com/weixin?query=NBA&type=2
Schedule http://weixin.sogou.com/weixin?query=NBA&type=2
Get Proxy 208.85.15.1:8181
Request Failed 5 Times http://weixin.sogou.com/weixin?query=NBA&type=2
Schedule http://weixin.sogou.com/weixin?query=NBA&type=2
Get Proxy 200.229.208.154:53281
Request Failed 6 Times http://weixin.sogou.com/weixin?query=NBA&type=2
Schedule http://weixin.sogou.com/weixin?query=NBA&type=2
Get Proxy 121.8.98.198:80
Request Failed 7 Times http://weixin.sogou.com/weixin?query=NBA&type=2
Schedule http://weixin.sogou.com/weixin?query=NBA&type=2
Get Proxy 85.15.179.5:8080

**Comment by goodbad3** [comment]
Get Proxy 103.216.144.17:8080
Request Failed 17 Times http://weixin.sogou.com/weixin?query=NBA&type=2
Schedule http://weixin.sogou.com/weixin?query=NBA&type=2
Get Proxy 43.252.73.91:80
Request Failed 18 Times http://weixin.sogou.com/weixin?query=NBA&type=2
Schedule http://weixin.sogou.com/weixin?query=NBA&type=2
Get Proxy 36.89.39.10:3128
Request Failed 19 Times http://weixin.sogou.com/weixin?query=NBA&type=2
Schedule http://weixin.sogou.com/weixin?query=NBA&type=2
Get Proxy 140.143.96.216:80
Request Failed 20 Times http://weixin.sogou.com/weixin?query=NBA&type=2

**Comment by goodbad3** [comment]
New Result <class 'weixin.request.WeixinRequest'>
New Result <class 'weixin.request.WeixinRequest'>
New Result <class 'weixin.request.WeixinRequest'>
New Result <class 'weixin.request.WeixinRequest'>
New Result <class 'weixin.request.WeixinRequest'>
New Result <class 'weixin.request.WeixinRequest'>
New Result <class 'weixin.request.WeixinRequest'>
New Result <class 'weixin.request.WeixinRequest'>
Schedule http://mp.weixin.qq.com/s?src=11&timestamp=1535085047&ver=1079&signature=cIOthA5tuY-8j3qF*H4NulqrGocKPriZ2s*7-5wKHq1tLSl9RgvQPAiWu-urdquz2yDWU4UK99SVAzH3s8zX9azI8kGr3h7pB86fdSyLs1NfH0VNqynjqOApGKdMyMBo&new=1
Request Failed 3 Times http://mp.weixin.qq.com/s?src=11&timestamp=1535085047&ver=1079&signature=cIOthA5tuY-8j3qF

**Comment by goodbad3** [comment]
数据保存不了

**Comment by Germey** [comment]
代理池的检测改成你要爬的页面的链接。另外免费代理质量不好，可以加一些付费代理进去
